import {Message} from "hubot"

class ReactionMessage extends Message {
   // Represents a message generated by an emoji reaction event
   // - this was copied from the hubot-slack api and should function similarly

   // type      - A String indicating 'reaction_added' or 'reaction_removed'
   // user      - A User instance that reacted to the item.
   // reaction  - A String identifying the emoji reaction.
   // item_user - A String indicating the user that posted the item.
   // item      - An Object identifying the target message, file, or comment item.
   // event_ts  - A String of the reaction event timestamp.
   constructor(type, user1, reaction, item_user, item, event_ts) {
      super(user);
      this.type = type;
      this.user = user1;
      this.reaction = reaction;
      this.item_user = item_user;
      this.item = item;
      this.event_ts = event_ts;
      this.type = this.type.replace('reaction_', '');
   }

};

export default ReactionMessage;

